[package]
name = "mediainfo"
description = "Rust bindings for libmediainfo"
version = "0.1.3"
authors = ["Erick Pires <pires@erickpires.com>"]
license = "MIT"
links = "mediainfo"
build = "build.rs"

[dependencies]
libc = "0.1"

[build-dependencies.pkg-config]
version = "0.3.9"
